version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - SA_PASSWORD=sPZxKpNKnzmi7P9GXGzdJDRoEBUbRmGjrCQn
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"  # External and internal port both set to 1433
    volumes:
      - sqlserverdata:/var/opt/mssql
      - ./sql-scripts:/var/opt/mssql/scripts  # Mounts your scripts folder
    entrypoint: /bin/bash /var/opt/mssql/scripts/entrypoint.sh

  dotnet-app:
    build:
      context: ./ThePantry
      dockerfile: Dockerfile
    container_name: api
    environment:
      - ConnectionStrings__DevelopmentDatabase=Server=tcp:pantry-sql-webapp.azurewebsites.net,1433;Initial Catalog=the_pantry;Persist Security Info=False;User ID=sa;Password=sPZxKpNKnzmi7P9GXGzdJDRoEBUbRmGjrCQn;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=True;Connection Timeout=30;    
    depends_on:
      - sqlserver
    ports:
      - "5000:5000"  # Both external and internal port set to 5000

  vite-react-app:
    build:
      context: ./pantry-frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "80:80"  # Maps frontend to localhost:80; change to "3000:80" if testing locally

volumes:
  sqlserverdata:
